### ISSUE TITLE
Settings not available from getOption()

### ISSUE THREAD

**Issue by christianseel** [Mark-H/ClientConfig#87]
In a 2.3.1 project I'm not able to access ClientConfig settings via `$modx->getOption('key',null,'not found');`.

While `$modx->getPlaceholder('+key')` worked.

After some debugging it turns out to be relaeted to the system event where the ClientConfig plugin is triggered. Changing it to "OnWebPageInit" fixed the issue in my snippet and the setting is accessible with getOption.

**Comment by studiorepublic** [comment]
Getting the same issue. A migxdb processor calls a snippet to send an email on publish. Not sure there's a system event applicable to this is there? Ended up including the plugin code in my snippet to process the settings

**Comment by minagerges** [comment]
Same occurs with me on 2.3.1

**Comment by markwillis82** [comment]
We still see this also. Is there any progress on this?

**Comment by zaigham** [comment]
:+1:

**Comment by Mark-H** [comment]
Pull requests are welcome ;)

Based on Chris' comments, the solution is to add more events to the plugin than just the OnHandleRequest, but I personally haven't researched if there's a reason this was reported for 2.3.1 but not before. 

As for the issue reported by @studiorepublic that seems a different issue where connector/processors indeed don't fire OnHandleRequest or any event at all. In #44 a suggested workaround is to invoke the OnHandleRequest rather than including the plugin code.

**Comment by sebastian-marinescu** [comment]
Is #115 fixing this issue?

**Comment by Mark-H** [comment]
> While OnWebPageInit worked for the frontend/snippets, the CMP fails now with "Class not found".

That has been fixed in 1.4.

Per #115 and #109 1.4 is also switched to use the OnMODXInit event instead of OnHandleRequest, which makes it work in a lot more different scenarios.
