### ISSUE TITLE
Checkbox resets value field to 1 if using a chunk

### ISSUE THREAD

**Issue by pixelstuff** [Mark-H/ClientConfig#99]
I was trying to use check boxes to insert social media icons on a website. (i.e. Show Facebook Icon, Show Twitter Icon, etc). Upon initial setup everything seemed to work fine and displayed on the website as it should, but as soon as I unchecked one of the boxes it reset the value of all check box fields to "1" instead of the chunk name previously in there.

In case it matters, the chunks themselves also had ClientConfig placeholders for the social media URL and name of the link. So the end users ultimately had the options to define the link name, the link url, and a check box to show or not show it on the site.

**Comment by Mark-H** [comment]
Hmm @pixelstuff I'm not sure I 100% follow how you had this set up, would you mind sharing your configuration for that field?

**Comment by Mark-H** [comment]
Closing due to insufficient information bug.

**Comment by Lefthandmedia** [comment]
In CC i made a setting [[++Mysetting]] , set it to checkbox and gave it a value ‘MyValue’.
Now save the configuration and go to client view check my new setting. Now the value ‘MyValue’ appears on the page… Great. Now i unchecked the chekbox and the value ‘MyValue’ is not on the page anymore Still… great.
But when i now check the checkbox again there is the value ‘1’ on the page instead of ‘MyValue’ ???

I’m using CC 2.1

**Comment by Mark-H** [comment]
A checkbox is either on or off. I'm inclined to say it should never return "MyValue", only 1 or empty.

**Comment by Lefthandmedia** [comment]
that may be so, but the what is the field 'value' for then? and it DOES give that value the first time it is set.

**Comment by Mark-H** [comment]
The value holds the (wait for it! :P) value of that field. With multi contexts enabled, the per-context value is stored in a separate table, but the value on the field is what's used for the global mode.   

When you uncheck it, the value is set to empty/0. When you check it again, the value is set to 1. 

I'd consider it's a bug that the checkbox type allows you to set a non-boolean value (or a value at all, really). The ability to define a value to use instead of 1 would be a separate feature request.

**Comment by Lefthandmedia** [comment]
Actualy the same as with a TV. A TV that has input type checkbox returns the set value for that TV not the mere fact its checked or not in in some boolean fashion. :)

**Comment by Mark-H** [comment]
If you feel so strongly about it, feel free to open a pull request or at the very least a separate feature request.
